make inject-project work on Ubuntu 16.04

diff --git a/scripts/inject-project b/scripts/inject-project
--- a/scripts/inject-project
+++ b/scripts/inject-project
@@ -1,13 +1,14 @@
 #!/bin/bash
 
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+GADGETOS_DIR="${SCRIPT_DIR}/.."
 
 SSH_PORT=27182
 
 # NOTE: this *needs* to be exported because it's read in the gadget sub-process
 export GADGET_ADDR=127.0.0.1:$SSH_PORT
 
-PUBLIC_KEY="${SCRIPT_DIR}/../gadget/package/gadget-setup-ssh-key/files/id_rsa.pub"
+PUBLIC_KEY="${GADGETOS_DIR}/gadget/package/gadget-setup-ssh-key/files/id_rsa.pub"
 
 TMP_DIR=$(mktemp -d /tmp/gadget-inject-project-XXXXXX)
 
@@ -44,6 +45,11 @@ echo "OUTPUT_DIR=$OUTPUT_DIR"
 [[ ! -x "$(which docker)" ]] && echo "ERROR: cannot find docker" && exit 1
 [[ ! -x "$(which gadget)" ]] && echo "ERROR: cannot find gadget" && exit 1
 
+echo
+echo "##################################################################################"
+echo "## making sure the overlay fs module is loaded (might require passord for sudo) ##"
+echo "##################################################################################"
+! lsmod |grep overlay -q && ! sudo modprobe overlay && echo "ERROR: cannot load module 'overlay'" && exit 1 || echo OK
 
 echo
 echo "###############################################"
@@ -92,12 +98,12 @@ echo "## copying data out ##"
 echo "######################"
 echo "creating tar file..."
 docker exec ${CONTAINER_NAME} mv /data/gadget.yml /
-docker exec ${CONTAINER_NAME} rmdir /data
+docker exec ${CONTAINER_NAME} rm -rf /data
 docker exec ${CONTAINER_NAME} tar cf /output/inject.tar --ignore-failed-read -C / \
 /etc/docker \
 /var/lib/docker \
 /gadget.yml
-cp ${OUTPUT_DIR}/inject.tar output/images/
+cp "${OUTPUT_DIR}/inject.tar" "${GADGETOS_DIR}/output/images/"
 
 echo
 echo "###################"
